; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Erthoric"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "EbiRom96"
#define MyAppURL "https://github.com/EbiRom96"
#define MyAppExeName "erthoric.py"
#define MyAppAssocName MyAppName + " Earthquake Monitor"
#define MyAppAssocExt ".py"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A1B2C3D4-E5F6-7890-ABCD-EF1234567890}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=LICENSE
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=Output
OutputBaseFilename=Erthoric_Setup
SetupIconFile=erthoric_icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "erthoric.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "README.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "Donation.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "requirements.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "erthoric_icon.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "ErthoricLauncher.exe"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\ErthoricLauncher.exe"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\ErthoricLauncher.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\ErthoricLauncher.exe"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
function InitializeSetup(): Boolean;
var
  PythonPath: string;
  ResultCode: Integer;
begin
  // Check if Python is installed
  if not RegQueryStringValue(HKLM, 'SOFTWARE\Python\PythonCore\3.11\InstallPath', '', PythonPath) then
  begin
    if not RegQueryStringValue(HKLM, 'SOFTWARE\Python\PythonCore\3.10\InstallPath', '', PythonPath) then
    begin
      if not RegQueryStringValue(HKLM, 'SOFTWARE\Python\PythonCore\3.9\InstallPath', '', PythonPath) then
      begin
        if not RegQueryStringValue(HKLM, 'SOFTWARE\Python\PythonCore\3.8\InstallPath', '', PythonPath) then
        begin
          if not RegQueryStringValue(HKLM, 'SOFTWARE\Python\PythonCore\3.7\InstallPath', '', PythonPath) then
          begin
            if not RegQueryStringValue(HKLM, 'SOFTWARE\Python\PythonCore\3.6\InstallPath', '', PythonPath) then
            begin
              // Python not found, ask user if they want to continue
              if MsgBox('Python 3.6+ is not detected on your system. Erthoric requires Python to run.' + #13#10 +
                        'Do you want to continue installation?', mbError, MB_YESNO) = IDNO then
              begin
                Result := False;
              end
              else
              begin
                Result := True;
              end;
            end
            else Result := True;
          end
          else Result := True;
        end
        else Result := True;
      end
      else Result := True;
    end
    else Result := True;
  end
  else Result := True;
end;